# Generated by Django 5.0.4 on 2024-05-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_id',
            new_name='id',
        ),
    ]
