# Generated by Django 5.0.4 on 2024-05-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0002_rename_room_id_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_backend.room'),
        ),
    ]
