# Generated by Django 5.0.4 on 2024-06-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0005_alter_userprofile_icon_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
